#!/usr/bin/env python3
"""Render ONBOARDING.md from scan JSON + verification marks + gotcha candidates.

  render.py [--scan FILE] [--out FILE] [--root DIR]
Defaults: scan = $ONBOARDER_HOME/scan.json, out = <root>/ONBOARDING.md.
Anything between <!-- onboarder:keep --> and <!-- /onboarder:keep --> is preserved.
"""
import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import onboarder_lib as ol  # noqa: E402

DEFAULT_KEEP = "\n_Human notes go here. This block survives every re-render._\n"
KIND_ORDER = ["install", "dev", "test", "build", "lint", "other", "deploy"]


def extract_keep(text):
    """Return the human block from an existing ONBOARDING.md, or None."""
    if not text:
        return None
    i = text.find(ol.KEEP_START)
    if i < 0:
        return None
    start = i + len(ol.KEEP_START)
    j = text.find(ol.KEEP_END, start)
    if j < 0:  # tolerate a pair of identical start markers
        j = text.find(ol.KEEP_START, start)
    if j < 0:
        return None
    return text[start:j]


def status_text(cmd, verified):
    v = verified.get(ol.norm_cmd(cmd))
    if not v:
        return "unverified"
    day = (v.get("at") or "")[:10]
    note = (": " + v["note"]) if v.get("note") else ""
    return ("verified ok %s%s" % (day, note)) if v.get("status") == "ok" else ("FAILED %s%s" % (day, note))


def fmt_bytes(n):
    for unit in ("B", "KB", "MB", "GB"):
        if n < 1024 or unit == "GB":
            return ("%d %s" % (n, unit)) if unit == "B" else ("%.1f %s" % (n, unit))
        n /= 1024.0


def render(scan, verified, gotchas, keep=None):
    name = os.path.basename(scan.get("root", "").rstrip("/")) or "this repo"
    stamp = scan.get("scanned_at", ol.now_iso())
    out = ["# Onboarding: %s" % name, "",
           "> Generated by codebase-onboarder from a static scan. Commands stay `unverified` until someone "
           "runs them and records the result. Re-run `/onboarder:refresh` after structural changes.", "",
           ol.KEEP_START + (keep if keep is not None else DEFAULT_KEEP) + ol.KEEP_END, ""]

    # Stack
    out += ["## Stack", ""]
    langs = scan.get("languages") or {}
    if scan.get("primary_language"):
        out.append("- Primary language: **%s**" % scan["primary_language"])
    if langs:
        out.append("- Languages (files): " + ", ".join("%s %d" % (k, v) for k, v in list(langs.items())[:8]))
    if scan.get("frameworks"):
        out.append("- Frameworks and tools: " + ", ".join(scan["frameworks"]))
    for k, v in (scan.get("runtime_versions") or {}).items():
        out.append("- Requires %s: `%s`" % (k, v))
    if scan.get("manifests"):
        out.append("- Manifests: " + ", ".join("`%s`" % m for m in scan["manifests"][:12]))
    if scan.get("entry_points"):
        out.append("- Entry points: " + ", ".join("`%s`" % e for e in scan["entry_points"][:12]))
    if scan.get("test_dirs") or scan.get("test_file_count"):
        out.append("- Tests: %s (%d test files)" % (
            ", ".join("`%s/`" % t for t in scan.get("test_dirs", [])[:8]) or "no test dirs",
            scan.get("test_file_count", 0)))
    for d in scan.get("docker") or []:
        bits = d.get("base_images") or d.get("services") or []
        out.append("- `%s`: %s" % (d["file"], ", ".join(bits) or "present"))
    out.append("")

    # Map
    out += ["## Map", "", "| Path | Files | Role (guessed) |", "|---|---|---|"]
    for d in (scan.get("dirs") or [])[:25]:
        out.append("| `%s` | %d | %s |" % (d["path"], d["files"], d["role"]))
    if scan.get("root_files"):
        out.append("")
        out.append("Root files: " + ", ".join("`%s`" % f for f in scan["root_files"][:20]))
    out.append("")

    # Commands
    out += ["## Commands", ""]
    cmds = sorted(scan.get("commands") or [], key=lambda c: (KIND_ORDER.index(c.get("kind", "other"))
                                                             if c.get("kind") in KIND_ORDER else 5))
    known = set()
    for c in cmds:
        known.add(ol.norm_cmd(c["cmd"]))
        tail = " (deploy: never run without explicit approval)" if c.get("kind") == "deploy" else ""
        out.append("- `%s` [%s] %s%s" % (c["cmd"], c.get("kind", "other"), status_text(c["cmd"], verified), tail))
    extra = [k for k in verified if k not in known]
    for k in sorted(extra):
        out.append("- `%s` [recorded] %s" % (k, status_text(k, verified)))
    if not cmds and not extra:
        out.append("- No candidate commands found.")
    out.append("")

    # Environment
    out += ["## Environment", ""]
    env = scan.get("env_vars") or {}
    if env:
        out.append("Variable names referenced (values never read):")
        out.append("")
        for k, srcs in list(env.items())[:40]:
            out.append("- `%s` (%s)" % (k, ", ".join(srcs[:3])))
        if len(env) > 40:
            out.append("- ... and %d more" % (len(env) - 40))
    else:
        out.append("- No environment variables detected.")
    out.append("")

    # CI
    out += ["## CI", ""]
    for w in scan.get("ci") or []:
        out.append("- **%s** (`%s`)%s" % (w["name"], w["file"],
                                          (": jobs " + ", ".join(w["jobs"])) if w.get("jobs") else ""))
        for r in w.get("run_steps", [])[:8]:
            out.append("  - `%s`" % r.replace("`", "'"))
    for o in scan.get("ci_other") or []:
        out.append("- `%s` (not parsed)" % o)
    if not scan.get("ci") and not scan.get("ci_other"):
        out.append("- No CI config found.")
    out.append("")

    # Hotspots
    out += ["## Hotspots", ""]
    hs = scan.get("hotspots") or {}
    if hs.get("churn"):
        out.append("Most-changed files (last 500 commits): " +
                   ", ".join("`%s` (%d)" % (h["path"], h["commits"]) for h in hs["churn"][:8]))
        out.append("")
    elif not scan.get("is_git"):
        out.append("Not a git repo, so no churn data.")
        out.append("")
    if hs.get("largest"):
        out.append("Largest files: " + ", ".join("`%s` (%s)" % (h["path"], fmt_bytes(h["bytes"]))
                                                 for h in hs["largest"][:8]))
        out.append("")

    # Gotchas
    out += ["## Gotchas", ""]
    live = [g for g in gotchas if g.get("status") != "dismissed"]
    if live:
        for g in live[-30:]:
            out.append("- %s%s" % (g["text"], " _(candidate)_" if g.get("status") == "candidate" else ""))
    else:
        out.append("- None recorded yet. The onboarder hook captures them as commands fail and get fixed.")
    out += ["", "---", "_Last updated: %s by codebase-onboarder._" % stamp, ""]
    return "\n".join(out)


def main(argv=None):
    p = argparse.ArgumentParser(description="Render ONBOARDING.md")
    p.add_argument("--root", default=".")
    p.add_argument("--scan")
    p.add_argument("--out")
    args = p.parse_args(argv)
    root = os.path.abspath(args.root)
    home = ol.home_dir(root)
    scan = ol.load_json(args.scan or ol.scan_path(home), {})
    if not scan:
        print("no scan found; run scan.py first", file=sys.stderr)
        return 1
    out = args.out or os.path.join(root, "ONBOARDING.md")
    existing = ""
    try:
        with open(out, encoding="utf-8") as f:
            existing = f.read()
    except OSError:
        pass
    text = render(scan, ol.load_verified(home), ol.load_gotchas(home), extract_keep(existing))
    ol.atomic_write(out, text)
    print("rendered %s" % out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
